version: '3.8'

networks:
  default:

services:
  db:
    image: mysql:5.7
    container_name: webchat-app
    ports:
      - 3309:3306
    volumes:
      - "./.data/db/mysql:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: webchat-app
